# Configuration for Label Actions - remove label id

more information needed:
  # Post a comment
  comment: >
    :wave: Hi there! It looks like you added a label to this discussion that is reserved for GitHub staff. I've removed this label.
    Beep boop, I am a
  discussions:
    # Remove labels
    unlabel:
      - 'more information needed'
      - 'fixed'
      - 'in backlog'
