name: 'Label Actions'

on:
  discussion:
    types: [labeled, created]

permissions:
  contents: read
  discussions: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - name: Check if employee
        id: check_employee
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.READ_GITHUB_ORG_MEMBERS_TOKEN }}
          result-encoding: string
          script: |
            try {
              const response = await github.rest.orgs.checkMembershipForUser({
                org: `github`,
                username: context.payload.sender.login
              });

              if (response.status === 204) {
                return 'true';
              } else {
                return 'false';
              }
            } catch (error) {
              console.log(error);
              return 'false';
            }
      
      - name : Label Actions
        if: ${{ steps.check_employee.outputs.result == 'true' }}
        uses: dessant/label-actions@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-path: '.github/label-actions.yml'
          process-only: ''
